repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: rubocop
        name: Rubocop
        language: system
        entry: bundle exec rubocop
        types: [ruby]
        exclude: \.lock|\.json
        stages:
          - commit
      - id: reek
        name: Reek
        language: system
        entry: bundle exec reek
        args: [--force-exclusion, --single-line, --sort-by=smelliness]
        types: [ruby]
        stages:
          - commit
      - id: prepare-commit-msg
        name: Prepare commit message
        entry: ruby hooks/prepare-commit-msg.rb
        language: system
        stages:
          - prepare-commit-msg
