repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: rubocop
        name: Rubocop
        language: system
        entry: bundle exec rubocop
        types: [ruby]
        exclude: \.lock
      - id: reek
        name: Reek
        language: system
        entry: bundle exec reek
        args: [--force-exclusion, --single-line, --sort-by=smelliness]
        types: [ruby]
