default_stages:
  - commit
repos:
  - repo: https://gitlab.com/dependabot-gitlab/pre-commit-hooks
    rev: 0.0.5
    hooks:
      - id: reek
      - id: rubocop
      - id: rspec
        args: [--tag=~integration]
        stages: [push]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: git-check
