---
detectors:
  IrresponsibleModule:
    enabled: false
  
  UtilityFunction:
    enabled: false

  NestedIterators:
    ignore_iterators:
      - yield_self
      - tap

  TooManyMethods:
    max_methods: 20

  TooManyStatements:
    max_statements: 10
    exclude:
      - initialize

  DuplicateMethodCall:
    max_calls: 2

exclude_paths:
  - bin
  - node_modules
  - vendor/**/*
