---
include:
  - app/**/*.rb
  - .definitions.rb
require:
  - dependabot/omnibus
domains: []
reporters:
  - rubocop
  - require_not_found
  - update_errors
plugins: []
require_paths: []
max_files: 5000
