---
include:
  - "**/*.rb"
  - Rakefile
  - Gemfile
exclude:
  - spec/**/*
  - vendor/**/*
  - ".bundle/**/*"
require:
  - dependabot/omnibus
domains: []
reporters:
  - rubocop
  - require_not_found
plugins: []
require_paths: []
max_files: 5000
