helmDefaults:
  atomic: true
  wait: true

repositories:
  - name: andrcuns
    url: https://andrcuns.github.io/charts

releases:
  - name: dependabot-gitlab
    namespace: dependabot
    chart: andrcuns/dependabot-gitlab
    version: 0.0.84
    installed: true
    values:
      - {{ requiredEnv "CI_ENVIRONMENT_SLUG" }}.yaml.gotmpl
