version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    commit-message:
      trailers:
        - changelog: dependency
    assignees:
      - andrcuns
    rebase-strategy: auto
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      trailers:
        - changelog: dependency
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: /spec/fixture/gitlab
    schedule:
      interval: daily
    commit-message:
      trailers:
        - changelog: development-dependency
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: /.gitlab/ci
    schedule:
      interval: daily
    commit-message:
      trailers:
        - changelog: development-dependency
    assignees:
      - andrcuns
