version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
      timezone: Europe/Riga
    commit-message:
      prefix: "dependency"
      prefix-development: "development-dependency"
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
      timezone: Europe/Riga
    commit-message:
      prefix: "dependency"
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: "/spec/fixture/gitlab"
    schedule:
      interval: daily
      time: "18:00"
      timezone: Europe/Riga
    commit-message:
      prefix: "development-dependency"
    assignees:
      - andrcuns
    auto-merge: true
