version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dependency
      prefix-development: development-dependency
    assignees:
      - andrcuns
    rebase-strategy: auto
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dependency
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: /spec/fixture/gitlab
    schedule:
      interval: daily
    commit-message:
      prefix: development-dependency
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: /.gitlab/ci
    schedule:
      interval: daily
    commit-message:
      prefix: development-dependency
    assignees:
      - andrcuns
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: daily
    commit-message:
      prefix: development-dependency
    assignees:
      - andrcuns
