version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "1:00"
    commit-message:
      include: scope
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "1:10"
    commit-message:
      include: scope
    assignees:
      - andrcuns
  - package-ecosystem: npm_and_yarn
    directory: "/"
    schedule:
      interval: daily
      time: "1:15"
    commit-message:
      include: scope
    assignees:
      - andrcuns
    