version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "17:00"
    commit-message:
      prefix: "dependency"
      prefix-development: "development-dependency"
    assignees:
      - andrcuns
    rebase-strategy: "auto"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "17:15"
    commit-message:
      prefix: "dependency"
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: "/spec/fixture/gitlab"
    schedule:
      interval: daily
    commit-message:
      prefix: "development-dependency"
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: "/.gitlab/ci"
    schedule:
      interval: daily
    commit-message:
      prefix: "development-dependency"
    assignees:
      - andrcuns
