version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dep
      prefix-development: dep-dev
      trailers:
        - changelog: dependency
      trailers-security:
        - changelog: security
    reviewers:
      - andrcuns
    auto-merge: true
    ignore:
      - dependency-name: sentry-ruby
      - dependency-name: sentry-sidekiq
