version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dep
      prefix-development: dep-dev
      trailers:
        - changelog: dependency
    reviewers:
      - andrcuns
    auto-merge: true
    ignore:
      - dependency-name: sentry-ruby
      - dependency-name: sentry-sidekiq
  - package-ecosystem: docker
    directory: /.gitlab/docker
    schedule:
      interval: daily
    commit-message:
      prefix: dep-dev
      trailers:
        - changelog: dependency
    reviewers:
      - andrcuns
    ignore:
      - dependency-name: ruby
        update-types: ["version-update:semver-major"]
