version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dep
      prefix-development: dep-dev
      trailers:
        - changelog: dependency
    assignees:
      - andrcuns
    auto-merge:
      ignore:
        - dependency-name: dependabot-omnibus
        - dependency-name: sentry-rails
        - dependency-name: sentry-ruby
        - dependency-name: sentry-sidekiq
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dep
      trailers:
        - changelog: dependency
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: /.gitlab/docker/test
    schedule:
      interval: daily
    commit-message:
      prefix: dep-dev
      trailers:
        - changelog: dependency
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: /.gitlab/docker/ci
    schedule:
      interval: daily
    commit-message:
      prefix: dep-dev
      trailers:
        - changelog: dependency
    assignees:
      - andrcuns
    auto-merge: true
