version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
    commit-message:
      include: scope
    assignees:
      - andrcuns
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "19:10"
    commit-message:
      include: scope
    assignees:
      - andrcuns
    