version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
      timezone: Europe/Riga
    commit-message:
      include: scope
    assignees:
      - andrcuns
    allow:
      - dependency-type: direct
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "19:10"
      timezone: Europe/Riga
    commit-message:
      include: scope
    assignees:
      - andrcuns
    