development:
  clients:
    default:
      database: <%= "#{ENV['MONGODB_DATABASE'] || 'dependabot_gitlab_development'}" %>
      hosts:
        - <%= ENV['MONGODB_URL'] || 'localhost:27017' %>
  options:
    app_name: DependabotGitlab

test:
  clients:
    default:
      database: <%= "#{ENV['MONGODB_DATABASE'] || 'dependabot_gitlab_test'}" %>
      hosts:
        - <%= ENV['MONGODB_URL'] || 'localhost:27017' %>
  options:
    app_name: DependabotGitlab

production:
  clients:
    default:
      database: <%= "#{ENV['MONGODB_DATABASE'] || 'dependabot_gitlab_production'}" %>
      hosts:
        - <%= ENV['MONGODB_URL'] || 'localhost:27017' %>
      options:
        user: <%= ENV['MONGDODB_USER'] %>
        password: <%= ENV['MONGODB_PASSWORD'] %>
  options:
    app_name: DependabotGitlab
