development:
  clients:
    default:
      database: dependabot_gitlab_development
      hosts:
        - <%= ENV['MONGODB_URL'] || 'localhost:27017' %>
  options:
    app_name: DependabotGitlab

test:
  clients:
    default:
      database: dependabot_gitlab_test
      hosts:
        - <%= ENV['MONGODB_URL'] || 'localhost:27017' %>
  options:
    app_name: DependabotGitlab

production:
  clients:
    default:
      database: dependabot_gitlab
      hosts:
        - <%= ENV['MONGODB_URL'] || 'localhost:27017' %>
  options:
    app_name: DependabotGitlab
