development:
  clients:
    default:
      database: dependabot_gitlab_development
      hosts:
        - <%= ENV['MONGODB_URL'] || 'localhost:27017' %>
      options:
        server_selection_timeout: 1
  options:
    app_name: DependabotGitlab

test:
  clients:
    default:
      database: dependabot_gitlab_test
      hosts:
        - <%= ENV['MONGODB_URL'] || 'localhost:27017' %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
        server_selection_timeout: 1
  options:
    app_name: DependabotGitlab
