apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  ports:
    - port: 4567
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - image: registry.gitlab.com/dependabot-gitlab/dependabot/gitlab-mock:master-latest
        name: gitlab
        ports:
        - name: http
          containerPort: 4567
          protocol: TCP
