# frozen_string_literal: true

describe DependabotController, :integration, type: :request, epic: :controllers, feature: "index page" do
  include_context "with dependabot helper"

  let(:project) { Project.create!(name: repo, configuration: Configuration.new(updates: updates_config)) }
  let(:config_entry) { updates_config.first }

  before do
    # mock return value in order to not fetch all projects generated by tests
    allow(Project).to receive(:not).and_return([project])

    UpdateJob.create!(
      project_id: project._id,
      package_ecosystem: config_entry[:package_ecosystem],
      directory: config_entry[:directory],
      cron: config_entry[:cron]
    )

    MergeRequest.create!(
      project_id: project._id,
      iid: 1,
      package_ecosystem: config_entry[:package_ecosystem],
      directory: config_entry[:directory],
      state: "opened"
    )
  end

  it "returns index page", :aggregate_failures do
    get("/")

    expect_status(200)
    expect(response.body).to include(project.name)
  end
end
