# frozen_string_literal: true

describe DependabotController, :integration, type: :request, epic: :controllers, feature: "index page" do
  let(:project) { create(:project_with_mr) }
  let(:config_entry) { updates_config.first }

  before do
    # mock return value in order to not fetch all projects generated by tests
    allow(Project).to receive(:not).and_return([project])
  end

  it "returns index page", :aggregate_failures do
    get("/")

    expect_status(200)
    expect(response.body).to include(project.name)
  end
end
