# frozen_string_literal: true

describe DependabotController, :integration, epic: :controllers, type: :controller do
  render_views

  include_context "with dependabot helper"

  let(:project) { Project.create!(name: repo, config: dependabot_config) }
  let(:config) { dependabot_config.first }

  before do
    # mock return value in order to not fetch all projects generated by tests
    allow(Project).to receive(:not).and_return([project])

    UpdateJob.create!(
      project_id: project._id,
      package_ecosystem: config[:package_ecosystem],
      directory: config[:directory],
      cron: config[:cron]
    )

    MergeRequest.create!(
      project_id: project._id,
      iid: 1,
      package_ecosystem: config[:package_ecosystem],
      directory: config[:directory],
      state: "opened"
    )
  end

  it "returns index page", :aggregate_failures do
    get(:index)

    expect_status(200)
    expect(response).to render_template(:index)
  end
end
