# Reusable rules
.mr: &mr
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
.main: &main
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web")'
.release: &release
  if: '$CI_COMMIT_TAG =~ /^v[0-9.]+$/ && $CI_PIPELINE_SOURCE == "push"'
.fork: &fork
  if: '$CI_PROJECT_ROOT_NAMESPACE != "dependabot-gitlab"'

.deploy_changes: &deploy_changes
  - app/**/*
  - config/**/*
  - db/**/*
  - kube/**/*
  - lib/tasks/dependabot.rake
  - public/**/*
  - config.ru
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Rakefile

# ======================================================================================================================
# Rules
# ======================================================================================================================
.rules:main:
  rules:
    - *mr
    - *release
    - *main

.rules:release:
  rules:
    - <<: *fork
      when: never
    - *release

.rules:deploy:
  rules:
    - <<: *fork
      when: never
    - <<: *main
      changes: *deploy_changes

.rules:dependency-scan:
  rules:
    - *main
    - <<: *mr
      changes:
        - Gemfile
        - Gemfile.lock

.rules:container-scan:
  rules:
    - *main
    - <<: *mr
      changes:
        - Dockerfile

.rules:allure-reports:
  rules:
    - <<: *fork
      when: never
    - *mr
    - *main

.rules:coverage:
  rules:
    - <<: *fork
      when: never
    - <<: *mr
      when: always
    - <<: *main
      when: always

.rules:build-image:
  rules:
    - <<: *main
      variables:
        LATEST_TAG: latest
    - <<: *release
      variables:
        LATEST_TAG: latest
    - *mr
