# Reusable rules
.mr: &mr
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
.master: &master
  if: '$CI_COMMIT_BRANCH == "master" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web")'
.release: &release
  if: '$CI_COMMIT_TAG =~ /^v[0-9.]+$/ && $CI_PIPELINE_SOURCE == "push"'
.fork: &fork
  if: '$CI_PROJECT_ROOT_NAMESPACE != "dependabot-gitlab"'
.fork-mr: &fork-mr
  if: '$CI_PROJECT_ROOT_NAMESPACE != "dependabot-gitlab" && $CI_PIPELINE_SOURCE == "merge_request_event"'

.deploy_changes: &deploy_changes
  - app/**/*
  - config/**/*
  - db/**/*
  - kube/**/*
  - lib/tasks/dependabot.rake
  - public/**/*
  - config.ru
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Rakefile

# ======================================================================================================================
# Rules
# ======================================================================================================================
.rules:main:
  rules:
    - *mr
    - *release
    - *master

.rules:main:e2e:
  rules:
    - <<: *fork-mr
      variables:
        DIND_IMAGE: docker:20.10.12-dind
    - <<: *mr
      changes:
        - Gemfile
        - Gemfile.lock
        - Dockerfile
    - <<: *mr
      when: manual
      allow_failure: true
    - *master
    - *release

.rules:release:
  rules:
    - <<: *fork
      when: never
    - *release

.rules:deploy:
  rules:
    - <<: *fork
      when: never
    - <<: *master
      changes: *deploy_changes

.rules:dependency-scan:
  rules:
    - *master
    - <<: *mr
      changes:
        - Gemfile
        - Gemfile.lock

.rules:container-scan:
  rules:
    - *master
    - <<: *mr
      changes:
        - Dockerfile

.rules:allure-reports:
  rules:
    - <<: *fork
      when: never
    - *master

.rules:build-image:
  rules:
    - <<: *fork-mr
      variables:
        BUILDKIT_IMAGE: moby/buildkit:v0.9.3
    - <<: *master
      variables:
        LATEST_TAG: latest
    - <<: *release
      variables:
        LATEST_TAG: latest
    - *mr

.rules:build-ci-image:
  rules:
    - <<: *fork-mr
      changes:
        - .gitlab/docker/ci/Dockerfile
      variables:
        BUILDKIT_IMAGE: moby/buildkit:v0.9.3
    - <<: *mr
      changes:
        - .gitlab/docker/ci/Dockerfile
    - <<: *master
      changes:
        - .gitlab/docker/ci/Dockerfile
      variables:
        LATEST_TAG: latest
