.ruby_runner:
  image: andrcuns/ruby:2.6.6-buster-10.5
  variables:
    BUNDLE_PATH: vendor/bundle
    BUNDLE_FROZEN: "true"
    BUNDLE_SUPPRESS_INSTALL_USING_MESSAGES: "true"
    BUNDLE_WITHOUT: development
  before_script:
    - bundle install
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/bundle
    policy: pull

.docker_runner:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  tags:
    - docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: /certs
    DOCKER_BUILDKIT: 1
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

.buildkit_runner:
  image:
    name: moby/buildkit:v0.7.2
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - mkdir -p /root/.docker
    - |
      cat <<- EOF > /root/.docker/config.json
      {
        "auths": {
          "registry.gitlab.com": {
            "auth": "$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)"
          }    
        }
      }
      EOF

.heroku_runner:
  image: finalgene/heroku-cli:7.42
  before_script:
    - apk add git
    - git fetch origin master && git checkout master
    - echo $NETRC > /root/.netrc
    - heroku git:remote -a dependabot-gitlab
